pub const SCREEN_SCALE: f32 = 3.0;

pub const ORIGINAL_SCREEN_WIDTH: f32 = 320.0;
pub const ORIGINAL_SCREEN_HEIGHT: f32 = 180.0;

pub const SCREEN_WIDTH: f32 = ORIGINAL_SCREEN_WIDTH * SCREEN_SCALE;
pub const SCREEN_HEIGHT: f32 = ORIGINAL_SCREEN_HEIGHT * SCREEN_SCALE;
